### ISSUE TITLE
Translatable Fields

### ISSUE THREAD

**Issue by iveliniliev90** [phoenix-lib/nova-nested-tree-attach-many#1]
HelloI have an issue where I am trying to attach records where the 'name' for each record is a translatable field (I'm using spatie/laravel-translatable and  optimistdigital/nova-translatable ).

And when the records are displayed.. i see only undefined, undefined,  undefined
![image_2020_12_02T13_31_31_475Z](https://user-images.githubusercontent.com/56114387/100882276-ac576400-34b7-11eb-8349-b7f3498b98fb.png)

Can you fix this please :)

**Comment by phoenix-lib** [comment]
Hello! can you provide some code where I can see how you use my package.
Today I`m tried to reproduce this problem.
- Installed packages spatie/laravel-translatable and optimistdigital/nova-translatable.
- Added trait `HasTranslations` to category model, added column `name` to $translatable variable.
- Added translations to the model and in my case the category names were translated with default localization.

**Comment by iveliniliev90** [comment]
Hello! This is my code
Category model -
![image](https://user-images.githubusercontent.com/56114387/101140039-10df0400-361b-11eb-84ce-56b9d2a817e2.png)


And your package - 
![image](https://user-images.githubusercontent.com/56114387/101140125-31a75980-361b-11eb-9337-e312d4f01ac1.png)

**Comment by iveliniliev90** [comment]
I think the problem is here
![image](https://user-images.githubusercontent.com/56114387/101141802-79c77b80-361d-11eb-8578-8aa2150676c5.png)

If I use STRING everything is find...but i need json for spatie/laravel-translatable

**Comment by phoenix-lib** [comment]
As a temporary solution you can add to your model:

`public function toArray()
{
   return array_merge(parent::toArray(),[ 'translated_name' => $this->name]);
}`

and when make field provide this field to method withLabelKey.

`
NestedTreeAttachManyField::make(__('OFFER_CATEGORIES'),'categories','App\Nova\Category')
       ->withLabelKey('translated_name')
`

To Fix this error I need change the tree build algorithm.

**Comment by iveliniliev90** [comment]
Thank you.
This fix my problem!
