### ISSUE TITLE
Cannot select options

### ISSUE THREAD

**Issue by angelinek** [phoenix-lib/nova-nested-tree-attach-many#10]
Hi,

I have make new installation just now.
But then I cannot select the options. Can you help me to have a look?
![image](https://user-images.githubusercontent.com/50966234/105589007-a3568500-5dcc-11eb-80c0-98ea7a1c4e2f.png)

My models:

`class ProductCategory extends Model implements HasMedia
{
    use HasMediaTrait, SoftDeletes;
    use ContentRebuildTriggerable;
    use NodeTrait;

    protected $table = 'product_categories';

    public function getLftName()
    {
        return '_lft';
    }

    public function getRgtName()
    {
        return '_rgt';
    }

    public function getParentIdName()
    {
        return 'parent_product_category_id';
    }

    // Specify parent id attribute mutator
    public function setParentAttribute($value)
    {
        $this->setParentIdAttribute($value);
    }

    public function products()
    {
        return $this->belongsToMany(Product::class, 'product_product_category');
    }

    public function parent_category()
    {
        return $this->belongsTo(self::class, 'parent_product_category_id');
    }

    public function sub_categories()
    {
        return $this->hasMany(self::class, 'parent_product_category_id');
    }

    // For spatie/laravel-query-builder to use
    // until they fix relationship being camelcased automatically
    public function parentCategory()
    {
        return $this->belongsTo(self::class, 'parent_product_category_id');
    }

    public function subCategories()
    {
        return $this->hasMany(self::class, 'parent_product_category_id');
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->width(130)
            ->height(130);

        $this->addMediaConversion('original');
    }

    public function registerMediaCollections()
    {
        $this->addMediaCollection('category_main')->singleFile();
        $this->addMediaCollection('category_banner')->singleFile();
    }
    public function saveQuietly(array $options = [])
    {
        return static::withoutEvents(function () use ($options) {
            return $this->save($options);
        });
    }`

My Resources:
`class ProductCategory extends Resource
{
    use NovaResourceAuthorizable;

    public static function permissionPrefix()
    {
        return 'category';
    }

    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = 'App\Sprii\Models\ProductCategory';

    /**
     * The logical group associated with the resource.
     *
     * @var string
     */
    public static $group = 'Catalog';

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'name';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id', 'name',
    ];

    /**
     * Get the displayable label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return 'Categories';
    }

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [

            Images::make('Image', 'category_main')
                ->onlyOnIndex(),

            ID::make()->sortable(),

            SluggableText::make('Name', 'name')->sortable()->readMore()->rules('max:255'),

            Slug::make('Slug', 'slug')->rules('max:255')->showOnIndex(false)
                ->slugUnique()->event('blur')
                ->slugModel(static::$model)->readonly(function ($request) {
                    return $request->isUpdateOrUpdateAttachedRequest();
                }),

            NestedTreeAttachManyField::make(__('Sub Categories'), 'sub_categories' ,'App\Nova\ProductCategory')->nullable(),

            AttachMany::make('Products'),

            BelongsToMany::make('Products'),
            Images::make('Carousel Image', 'category_main') // second parameter is the media collection name
                // ->conversionOnIndexView('thumb') // conversion used to display the image
                ->conversionOnDetailView('thumb') // conversion used on the model's view
                ->conversionOnIndexView('thumb') // conversion used to display the image on the model's index page
                ->conversionOnForm('thumb') // conversion used to display the image on the model's form
                ->singleImageRules('dimensions:min_width=100,max_width=1700,max_height=1700', 'max:1024', 'mimes:jpeg, jpg, png, gif, webp, ico')
                ->hideFromIndex(),

            Images::make('Banner Image', 'category_banner')
                ->conversionOnDetailView('thumb')
                ->conversionOnIndexView('thumb')
                ->conversionOnForm('thumb')
                ->singleImageRules('dimensions:min_width=100,max_width=1700,max_height=1700', 'max:1024', 'mimes:jpeg, jpg, png, gif, webp, ico')
                ->hideFromIndex(),

            Boolean::make('Active', 'is_active'),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [
            (new ActivateDeactivate)->onlyOnTableRow(),
        ];
    }
}
`
This is my db, as you can see, a&b should be active
![image](https://user-images.githubusercontent.com/50966234/105596479-ac485600-5dce-11eb-814a-6092f581b24c.png)

**Comment by phoenix-lib** [comment]
Hi, by default if model has column 'is_active' and if this column is not true - node will be disabled in tree.

You can disable this behavior with method ->withActiveKey('not_exists_column').

If you need this ability - column 'is_active' should has boolean type.

I think this ability needs to be improved so that everyone can choose which value is true and which is false.

**Comment by angelinek** [comment]
when i create this node, is_active is false, but then later I edit it to be true, it is still disabled

**Comment by phoenix-lib** [comment]
Hi, added method ->isActiveFalseValue( $value = true ) it is  solve your problem.

You can used it ->isActiveFalseValue( 0 )

Need upgrade to 1.4.2 version
