### ISSUE TITLE
Selecting parent does not result in selection of children ?

### ISSUE THREAD

**Issue by AbetaNL** [phoenix-lib/nova-nested-tree-attach-many#11]
Hello, have been experimenting with this package and I really like it so far! I currently run into the following problem though. When I select a parent this does not result in the selection of the children, which does seem to be the case at the documentation of Vue Treeselect. https://vue-treeselect.js.org/#basic-features

When I select "Parent" I expect the children to be selected as well. Currently I have this:
![image](https://user-images.githubusercontent.com/25418904/105709541-246d6380-5f16-11eb-9797-fca5ec6d1450.png)

My db structure looks like this:
![image](https://user-images.githubusercontent.com/25418904/105709631-4535b900-5f16-11eb-98d7-8da319e60c2c.png)

And my code like this:
` NestedTreeAttachManyField::make('Offer Categories',"fields","App\Nova\TemplateField")
                        ->searchable(true)
                        ->withChildrenKey('children')
                        ->withAlwaysOpen(true)
                        ->withActiveKey(true)`

I could not find anything in the documentation about this. Is this possible, or am I doing something wrong?
Cheers!

**Comment by phoenix-lib** [comment]
Hi, the "flatten" parameter is responsible for this option. By default in vue-treeselect flatten is disabled. 
In my package flatten is enabled.

I'll try to explain:

- Wallpapers [1]
- - Brands [2]
- - - Some Brand [3]

When we has structure as in example and select "Wallpapers", visual selected will be three categories but attached will be only "Wallpapers[1]".

- Wallpapers [1]
- - Brands [2]
- - - Some Brand [3]
- - - Another Brand [4]
- 
When we has structure as in this example and select "Some Brand[3]" attached will be "Some Brand[3]"

But if we select Some Brand [3] and Another Brand [4] attached will be Wallpapers [1].

After tests I enable flatten to avoid confusion when saving.

**Comment by phoenix-lib** [comment]
If you need the behavior that I described above, write message and I will add method for change it.

**Comment by AbetaNL** [comment]
Hi @phoenix-lib , thank you for the explanation! If it would not be too much effort I would really like to be able to adjust the "flatten" setting from within the options!

**Comment by phoenix-lib** [comment]
Hi, added method withFlatten - you can use it

Upgrade to 1.4.2 version

**Comment by AbetaNL** [comment]
Works great! Thanks for the effort!
