### ISSUE TITLE
Nova indexQuery not respected

### ISSUE THREAD

**Issue by ThisIsMyFavouriteJar** [phoenix-lib/nova-nested-tree-attach-many#13]
Hello,

Love the package. I noticed that it does not respect the indexQuery which is placed on the Nova Resource. I have the following in my Nova Category Resource:

`    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->where('platform_id', $request->user()->platform->id);
    }`

However, the tree shows all categories, regardless of the user. So all users can see all categories, even if they belong to different users/platforms. Is this a bug, or should I overcome this problem in another way, e.g. by adding a where to my relationship?

**Comment by AbetaNL** [comment]
Hi @phoenix-lib , do you perhaps have any suggestions how I can deal with this? Cheers!

**Comment by phoenix-lib** [comment]
Hi, you can use this feature after upgrade to 1.5.0 version.
