### ISSUE TITLE
Can't view records with categories in them.

### ISSUE THREAD

**Issue by CorySheppard** [phoenix-lib/nova-nested-tree-attach-many#23]
Hey, was wondering if you could help me out a bit. I'm getting a "Server Error" when I try to look at or try to edit records in my Products table, but only ones that have categories selected. Furthermore, I am only getting this error when I attempt to view or edit the records on my live site deployment. Locally it's fine. Here's what I get in the F12 console, 

```
Failed to load resource: /nova-api/product-categories/2/update-fields?editing=true&edit
Mode=update&viaResource=&viaResourceId=&viaRelationship= the server responded with a status of 500 ()
```
and
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at a.<anonymous> (app.js?id=1c7abbbe8cf05b9e2ece:1)
    at x (app.js?id=1c7abbbe8cf05b9e2ece:1)
    at Generator._invoke (app.js?id=1c7abbbe8cf05b9e2ece:1)
    at Generator.e.<computed> [as next] (app.js?id=1c7abbbe8cf05b9e2ece:1)
    at o (app.js?id=1c7abbbe8cf05b9e2ece:1)
    at app.js?id=1c7abbbe8cf05b9e2ece:1
```

Happy to try and supply more information, screenshots, code snippets, etc. Just ask.

**Comment by phoenix-lib** [comment]
Hello, could you enable debug mode in production, then try to reproduce bug and see what kind of error are logged in logs?  ${doc_root}/storage/logs/laravel.log

**Comment by CorySheppard** [comment]
Hey, we ended up using Vapor-UI to view the errors it was logging in production. Turned out to be an issues with images uploading S3, sorry to have wasted your time. Great plug-in by the way, saved us a lot of time.
