### ISSUE TITLE
Support hasMany and belongsTo

### ISSUE THREAD

**Issue by angelinek** [phoenix-lib/nova-nested-tree-attach-many#5]
Hi,

Is it possible for this to support hasMany and belongsTo relationship?

Would like to implement this on choosing parent category and sub-category

Thanks !

**Comment by phoenix-lib** [comment]
Hi, in experimental mode I`m added support of HasMany and BelongsTo relations.
I need some time to think and refactor handlers for relations.


How to use for BelongsTo

`NestedTreeAttachManyField::make(__('CATEGORY_PARENT'), 'parent' ,'App\Nova\Category')->useSingleSelect()`

->useSingleSelect is required - if don`t add this option in save process will throw DomainException.



How to use for HasMany

`NestedTreeAttachManyField::make(__('SUB_CATEGORIES'), 'children' ,'App\Nova\Category')`

How can you see that all you need to do is just specify relation.



!!Warning for use HasMany relation!!

In unqualified hands this feature can broke your tree.

I will try to explain on this example:

We has tree with structure.

-Node 1-1
--Node 1-2
---Node 1-3 - now we edit this node
----Node 1-4 - selected
-----Node 1-5 - select this item
-Node 2-1 - select this item
--Node 2-2
-Node 3-1 - select this item


When we save form new structure will be:


-Node 1-1
--Node 1-2
---Node 1-3 - we are here
----Node 1-4 - selected
----Node 1-5 - selected
----Node 2-1 - selected
-----Node 2-2
----Node 3-1 - selected


All selected nodes in previous step now is a children of the Node 1-3 where we was.


You can attach sub-categories from another parent branches, children nodes and siblings, but you can`t attach parent from current branch where we now. If you want to do this - you can do this in two or three steps.
This behavior was done for tree safety.


I think that this package is not intended for tree management and it is better to make a package with drag and drop support, but as an experiment you can try using the current version.

**Comment by angelinek** [comment]
Hi, is it possible that when I delete the parent node. the parent_id of the children will be set to null instead of deleting the children node together with parents?

Thanks for your help!

**Comment by angelinek** [comment]
Thanks alot!!

Another note here is that if u are using laravel version older than 8, when u use for belongsto relationship, u will need to add this function inside the model
```
public function saveQuietly(array $options = [])
    {
        return static::withoutEvents(function () use ($options) {
            return $this->save($options);
        });
    }
```

**Comment by phoenix-lib** [comment]
Hi, added support for old laravel versions.
Upgrade to 1.4.1 version.
Thanks for message 👍
