### ISSUE TITLE
RelationHandler for relation: Staudenmeir\EloquentEagerLimit\Relations\BelongsToMany is not registered

### ISSUE THREAD

**Issue by digitalunityca** [phoenix-lib/nova-nested-tree-attach-many#6]
Hi,

Git this error after package upgrade from 1.2 to 1.3

![image](https://user-images.githubusercontent.com/38138816/104624515-ab425680-5661-11eb-8909-00a9b02a70af.png)

Laravel Nova version 3.19.1
Laravel Version 8.22.1

Steps to reproduce:
Upgrade to last version 1.3

Thanks :)

**Comment by phoenix-lib** [comment]
Hi, added support of custom relations that extends base relations you should upgrade package to version 1.3.1
Thanks for message. 👍
