### ISSUE TITLE
Поддержка morphMany

### ISSUE THREAD

**Issue by ExsyDev** [phoenix-lib/nova-nested-tree-attach-many#7]
Привет, есть такая проблема, я сделал полиморфную связь категорий таким образом:

`public function categories()
    {
        return $this->morphToMany(Category::class, 'attributeable');
    }
`

В ресурсе у меня идет так:

`NestedTreeAttachManyField::make(__('Categories'), 'categories', "App\Nova\Category"),`

При создании записи получаю ошибку:

```SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_id' in 'field list' (SQL: insert into `attributeables` (`attributeable_id`, `attributeable_type`, `category_id`) values (15, App\Attribute, 1))```

Вопрос, как убрать category_id и чтобы вставляло так:

```(SQL: insert into `attributeables` (`attributeable_id`, `attributeable_type`) values (1, App\Category))```

**Comment by phoenix-lib** [comment]
Привет, тут проблема не в поддержке MorphToMany.

                                    Attribute                     Attribute                Category
     Таблица             ID сущности            Тип сущности       ID категории
`attributeables` (`attributeable_id`, `attributeable_type`, `category_id`)

Если сделать как ты просишь - это уже будет не MorphToMany

Напиши какой кейс пытаешься решить, может быть смогу подсказать.

Так же рекомендую почитать доку по полиморфным связям.
https://laravel.com/docs/8.x/eloquent-relationships#one-to-many-polymorphic-relations

**Comment by ExsyDev** [comment]
@phoenix-lib я пытаюсь сделать категории для атрибутов, атрибуты должны цепляться к категориям и продуктам, потому и сделал полиморфную связь

**Comment by phoenix-lib** [comment]
offers
    --- id - integer
    --- name - string

categories
    --- id - integer
    --- name - string

attributes
   --- id - integer
   --- name - string

attributeables
   --- attribute_id - integer
   --- attributeable_id - integer
   --- attributeable_type - string

В модельках Offer и Category:
public function attributes() { return $this->morphToMany(Attribute::class, 'attributeable'); }

Однако у меня возникает вопрос, насколько это удобно будет)) 

Если в каталоге 5 товаров, то еще можно такую схему применять когда индивидуально к товару можно прикреплять атрибуты. Для каталога с несколькими тысячами товаров не говоря про особо крупные каталоги - это будет очень большая боль.

Мой пакет такое без серьезных доработок не потянет, можешь попробовать вот этот:
https://github.com/dillingham/nova-attach-many

**Comment by ExsyDev** [comment]
@phoenix-lib спасибо большое:)
