### ISSUE TITLE
Не работает правило "required"

### ISSUE THREAD

**Issue by ExsyDev** [phoenix-lib/nova-nested-tree-attach-many#8]
Если применять валидацию к полю, то поле игнорирует валидацию (если ничего не выбирать из поля) и пропускает создание ресурса:

``NestedTreeAttachManyField::make(__('Categories'), 'categories', "App\Nova\Category")->rules('required'),``

Как это можно решить?

**Comment by phoenix-lib** [comment]
Привет, не доходили руки добавить валидацию в version 1.4.0 появилась такая возможность, обновись.
